# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer import util


class Field(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self,
                 display_text=None,
                 elasticsearch_name=None,
                 is_facet_value=None):  # noqa: E501
        """Field - a model defined in Swagger

        :param display_text: The display_text of this Field.  # noqa: E501
        :type display_text: str
        :param elasticsearch_name: The elasticsearch_name of this Field.  # noqa: E501
        :type elasticsearch_name: str
        :param is_facet_value: The is_facet_value of this Field.  # noqa: E501
        :type is_facet_value: bool
        """
        self.swagger_types = {
            'display_text': str,
            'elasticsearch_name': str,
            'is_facet_value': bool
        }

        self.attribute_map = {
            'display_text': 'display_text',
            'elasticsearch_name': 'elasticsearch_name',
            'is_facet_value': 'is_facet_value'
        }

        self._display_text = display_text
        self._elasticsearch_name = elasticsearch_name
        self._is_facet_value = is_facet_value

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Field of this Field.  # noqa: E501
        :rtype: Field
        """
        return util.deserialize_model(dikt, cls)

    @property
    def display_text(self):
        """Gets the display_text of this Field.

        The text displayed in the dropdown.  # noqa: E501

        :return: The display_text of this Field.
        :rtype: str
        """
        return self._display_text

    @display_text.setter
    def display_text(self, display_text):
        """Sets the display_text of this Field.

        The text displayed in the dropdown.  # noqa: E501

        :param display_text: The display_text of this Field.
        :type display_text: str
        """

        self._display_text = display_text

    @property
    def elasticsearch_name(self):
        """Gets the elasticsearch_name of this Field.

        The Elasticsearch field name.  # noqa: E501

        :return: The elasticsearch_name of this Field.
        :rtype: str
        """
        return self._elasticsearch_name

    @elasticsearch_name.setter
    def elasticsearch_name(self, elasticsearch_name):
        """Sets the elasticsearch_name of this Field.

        The Elasticsearch field name.  # noqa: E501

        :param elasticsearch_name: The elasticsearch_name of this Field.
        :type elasticsearch_name: str
        """

        self._elasticsearch_name = elasticsearch_name

    @property
    def is_facet_value(self):
        """Gets the is_facet_value of this Field.

        If this is a facet or a facet value field.  # noqa: E501

        :return: The is_facet_value of this Field.
        :rtype: bool
        """
        return self._is_facet_value

    @is_facet_value.setter
    def is_facet_value(self, is_facet_value):
        """Sets the is_facet_value of this Field.

        If this is a facet or a facet value field.  # noqa: E501

        :param is_facet_value: The is_facet_value of this Field.
        :type is_facet_value: bool
        """

        self._is_facet_value = is_facet_value
