openapi: 3.0.0
info:
  title: Data Explorer Service
  description: API Service that reads from Elasticsearch.
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  version: 0.0.1
paths:
  /dataset:
    get:
      description: 'Gets dataset information, such as name.'
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DatasetResponse'
      tags:
        - Dataset
  /facets:
    get:
      description: Returns facets.
      parameters:
        - name: filter
          description: >
            filter represents selected facet values. Elasticsearch query will be
            run only over selected facet values. filter is an array of strings,
            where each string has the format "facetName=facetValue". Example url
            /facets?filter=Gender=female,Region=northwest,Region=southwest
          in: query
          schema:
            type: array
            style: pipeDelimited
            items:
              type: string
        - name: extraFacets
          description: >-
            extraFacets represents the fields selected from the field search
            box. extraFacets is a list of Elasticsearch field names. In the
            returned list of facets, the extra facets will come before the
            facets from ui.json.
          in: query
          schema:
            type: array
            style: pipeDelimited
            items:
              type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FacetsResponse'
      tags:
        - Facets
  /fields:
    get:
      description: Returns dataset fields for field search.
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FieldsResponse'
      tags:
        - Fields
  /exportUrl:
    post:
      description: >
        Creates and returns a signed URL to a GCS zip file of JSON files. The
        JSON files represent entities to be exported to a Saturn workspace.
        https://bvdp-saturn-prod.appspot.com/#import-data may be called with the
        url parameter set to this url. For each JSON file,
        https://rawls.dsde-prod.broadinstitute.org/#!/entities/create_entity may
        be called with the JSON as the POST body.
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExportUrlResponse'
      tags:
        - ExportUrl
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cohortName:
                  type: string
                filter:
                  type: array
                  style: pipeDelimited
                  items:
                    type: string
components:
  schemas:
    DatasetResponse:
      description: Dataset information.
      properties:
        name:
          type: string
        enableFieldSearch:
          type: boolean
    FacetsResponse:
      description: Results from a faceted search.
      properties:
        facets:
          type: array
          items:
            $ref: '#/components/schemas/Facet'
        count:
          type: integer
          description: >
            Number of entities represented by current facet selection. For
            example, this could be 40, representing 40 people.
    Facet:
      description: >
        A facet. For example, the Gender facet would include the facet name
        "Gender", as well as counts for all possible values.
      properties:
        name:
          type: string
          description: 'Facet name, for example, "Gender".'
        description:
          type: string
          description: Optional facet description.
        values:
          type: array
          items:
            $ref: '#/components/schemas/FacetValue'
    FacetValue:
      description: 'A facet value, for example, "Male"/34.'
      properties:
        name:
          type: string
          description: 'Facet value name, for example, "Male".'
        count:
          type: integer
          description: Facet value count.
    ExportUrlResponse:
      description: Information for sending data to Saturn
      properties:
        url:
          type: string
          description: URL-encoded signed URL of GCS file containing entities to export.
        authorization_domain:
          type: string
          description: Optional FireCloud authorization domain
    FieldsResponse:
      description: Dataset fields for field search.
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    Field:
      description: >
        A field. For example, a BigQuery Gender column could include the field
        name "Gender", description "Sex at birth" and elasticsearch field name
        "project_id.dataset_id.table_name.Gender".
      properties:
        name:
          type: string
          description: 'Field name, for example, "Gender".'
        description:
          type: string
          description: Optional field description.
        elasticsearch_name:
          type: string
          description: The Elasticsearch field name.
